# Generated by Django 3.2.14 on 2023-06-07 10:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IntakeForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('is_trashed', models.BooleanField(default=False)),
                ('title', models.CharField(max_length=200, unique=True)),
            ],
            options={
                'verbose_name_plural': 'IntakeForms',
            },
        ),
        migrations.CreateModel(
            name='IntakeFormSubmissions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('is_trashed', models.BooleanField(default=False)),
                ('submission_data', models.JSONField()),
                ('version', models.FloatField()),
                ('intake_form', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submission_intake_form', to='intake_forms.intakeform')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='intake_form_submission_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'IntakeFormSubmissions',
            },
        ),
        migrations.CreateModel(
            name='IntakeFormFields',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('is_trashed', models.BooleanField(default=False)),
                ('field_name', models.CharField(max_length=200)),
                ('field_type', models.CharField(max_length=50)),
                ('options', models.JSONField(blank=True, null=True)),
                ('version', models.FloatField()),
                ('intake_form', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='field_intake_form', to='intake_forms.intakeform')),
            ],
            options={
                'verbose_name_plural': 'IntakeFormFields',
            },
        ),
    ]
