# Generated by Django 3.2.14 on 2023-06-08 09:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('intake_forms', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='intakeformsubmissions',
            old_name='user',
            new_name='submitted_user',
        ),
        migrations.RemoveField(
            model_name='intakeformfields',
            name='created',
        ),
        migrations.RemoveField(
            model_name='intakeformfields',
            name='intake_form',
        ),
        migrations.RemoveField(
            model_name='intakeformfields',
            name='is_trashed',
        ),
        migrations.RemoveField(
            model_name='intakeformfields',
            name='modified',
        ),
        migrations.RemoveField(
            model_name='intakeformfields',
            name='version',
        ),
        migrations.RemoveField(
            model_name='intakeformsubmissions',
            name='created',
        ),
        migrations.RemoveField(
            model_name='intakeformsubmissions',
            name='intake_form',
        ),
        migrations.RemoveField(
            model_name='intakeformsubmissions',
            name='is_trashed',
        ),
        migrations.RemoveField(
            model_name='intakeformsubmissions',
            name='modified',
        ),
        migrations.RemoveField(
            model_name='intakeformsubmissions',
            name='version',
        ),
        migrations.CreateModel(
            name='IntakeFormFieldVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('is_trashed', models.BooleanField(default=False)),
                ('version', models.FloatField()),
                ('intake_form', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='intake_form_field_version_form', to='intake_forms.intakeform')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='intake_form_field_version_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'IntakeFormVersion',
                'unique_together': {('intake_form', 'version')},
            },
        ),
        migrations.AddField(
            model_name='intakeformfields',
            name='form_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='intake_form_fields_form_version', to='intake_forms.intakeformfieldversion'),
        ),
        migrations.AddField(
            model_name='intakeformsubmissions',
            name='form_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='intake_form_submission_form_version', to='intake_forms.intakeformfieldversion'),
        ),
    ]
