# Generated by Django 3.2.14 on 2023-06-09 07:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('intake_forms', '0003_auto_20230608_1221'),
    ]

    operations = [
        migrations.AddField(
            model_name='intakeformfields',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='intakeformfields',
            name='is_trashed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='intakeformfields',
            name='modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
