# Generated by Django 3.2.14 on 2023-06-09 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('intake_forms', '0005_alter_intakeform_title'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='intakeformfieldversion',
            unique_together=set(),
        ),
    ]
