# Generated by Django 3.2.14 on 2023-06-16 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intake_forms', '0006_alter_intakeformfieldversion_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='intakeformfields',
            name='meta_data',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
