# Generated by Django 3.2.14 on 2023-06-22 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intake_forms', '0008_auto_20230622_0811'),
    ]

    operations = [
        migrations.AddField(
            model_name='intakeform',
            name='form_slug',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='intakeform',
            name='title',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
