# Generated by Django 3.2.14 on 2022-12-26 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('is_trashed', models.BooleanField(default=False)),
                ('media', models.FileField(blank=True, upload_to='uploded/')),
                ('title', models.CharField(blank=True, max_length=1000, null=True)),
                ('is_done', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'TestMedia',
            },
        ),
    ]
