# Generated by Django 3.2.14 on 2023-02-03 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0004_notifications_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notifications',
            name='notification_type',
            field=models.CharField(choices=[('job_edited', 'job_edited'), ('job_proposal', 'job_proposal'), ('job_submit_work', 'job_submit_work'), ('job_work_approver', 'job_work_approver'), ('job_completed', 'job_completed'), ('in_house_assigned', 'in_house_assigned'), ('invite_accepted', 'invite_accepted'), ('asset_uploaded', 'asset_uploaded')], default='job_proposal', max_length=60),
        ),
    ]
