# Generated by Django 3.2.14 on 2023-03-23 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='story_id',
            field=models.IntegerField(default=1, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tag',
            name='tag_id',
            field=models.IntegerField(default=1, unique=True),
            preserve_default=False,
        ),
    ]
