# Generated by Django 3.2.14 on 2023-03-23 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0002_auto_20230323_1127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='image',
            field=models.URLField(blank=True, null=True),
        ),
    ]
