# Generated by Django 3.2.14 on 2023-03-24 12:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0004_auto_20230324_0749'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('is_trashed', models.BooleanField(default=False)),
                ('category_id', models.IntegerField(unique=True)),
                ('title', models.CharField(max_length=200)),
                ('is_unique', models.BooleanField(default=True)),
                ('description', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('community', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='category_community', to='community.community')),
            ],
            options={
                'verbose_name_plural': 'Category',
            },
        ),
        migrations.CreateModel(
            name='StoryTagAnalytic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('story', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='community.story')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='community.tag')),
            ],
        ),
        migrations.CreateModel(
            name='StoryCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='community.category')),
                ('story', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='community.story')),
            ],
        ),
        migrations.AddField(
            model_name='story',
            name='analytic',
            field=models.ManyToManyField(related_name='story_analytic', through='community.StoryTagAnalytic', to='community.Tag'),
        ),
        migrations.AddField(
            model_name='story',
            name='category',
            field=models.ManyToManyField(related_name='story_category', through='community.StoryCategory', to='community.Category'),
        ),
    ]
