# Generated by Django 3.2.14 on 2023-03-24 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0005_auto_20230324_1219'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='storycategory',
            name='category',
        ),
        migrations.RemoveField(
            model_name='storycategory',
            name='story',
        ),
        migrations.RemoveField(
            model_name='storytaganalytic',
            name='story',
        ),
        migrations.RemoveField(
            model_name='storytaganalytic',
            name='tag',
        ),
        migrations.RemoveField(
            model_name='story',
            name='analytic',
        ),
        migrations.RemoveField(
            model_name='story',
            name='category',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='StoryCategory',
        ),
        migrations.DeleteModel(
            name='StoryTagAnalytic',
        ),
    ]
