# Generated by Django 3.2.14 on 2023-03-28 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0008_auto_20230328_0723'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='category',
            unique_together={('community', 'title')},
        ),
        migrations.AlterUniqueTogether(
            name='tag',
            unique_together={('community', 'title')},
        ),
    ]
