# Generated by Django 3.2.14 on 2023-04-13 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0012_auto_20230412_1116'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='community',
            name='channel',
        ),
    ]
