# Generated by Django 3.2.14 on 2023-04-13 12:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0013_remove_community_channel'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommunitySetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('is_trashed', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('channel', models.ManyToManyField(related_name='community_setting_channel', through='community.CommunityChannel', to='community.Channel')),
                ('community', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='community_setting_community', to='community.community')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='communitychannel',
            name='community',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='community_channel_community', to='community.communitysetting'),
        ),
    ]
