# Generated by Django 3.2.14 on 2023-04-13 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0014_auto_20230413_1254'),
    ]

    operations = [
        migrations.RenameField(
            model_name='communitychannel',
            old_name='community',
            new_name='community_setting',
        ),
    ]
