# Generated by Django 3.2.14 on 2023-04-18 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0015_rename_community_communitychannel_community_setting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='image',
            field=models.TextField(blank=True, null=True),
        ),
    ]
