# Generated by Django 3.2.14 on 2023-04-26 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0017_program'),
    ]

    operations = [
        migrations.CreateModel(
            name='CopyCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('is_trashed', models.BooleanField(default=False)),
                ('title', models.CharField(max_length=200)),
                ('subject_line', models.CharField(max_length=200)),
                ('body', models.TextField()),
                ('notes', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'CopyCodes',
            },
        ),
    ]
