# Generated by Django 3.2.14 on 2023-04-26 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0018_copycode'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreativeCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('is_trashed', models.BooleanField(default=False)),
                ('title', models.CharField(max_length=200)),
                ('file_name', models.CharField(max_length=200)),
                ('format', models.CharField(max_length=10)),
                ('creative_theme', models.CharField(max_length=200)),
                ('horizontal_pixel', models.CharField(max_length=10)),
                ('vertical_pixel', models.CharField(max_length=10)),
                ('duration', models.CharField(max_length=10)),
                ('link', models.URLField(max_length=500)),
                ('notes', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'CreativeCodes',
            },
        ),
    ]
