# Generated by Django 3.2.14 on 2023-05-04 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0020_alter_communitysetting_community'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='description',
        ),
    ]
