# Generated by Django 3.2.14 on 2023-05-26 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0021_alter_communitysetting_community'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='story_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
