# Generated by Django 3.2.14 on 2023-06-12 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0022_story_story_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Audience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('is_trashed', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=255)),
                ('row_count', models.BigIntegerField()),
                ('available', models.BigIntegerField()),
                ('opted_out', models.BigIntegerField()),
                ('non_mobile', models.CharField(max_length=100)),
                ('routes', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField()),
            ],
            options={
                'verbose_name_plural': 'Audiences',
            },
        ),
    ]
