# Generated by Django 3.2.14 on 2023-06-12 14:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0023_audience'),
    ]

    operations = [
        migrations.AddField(
            model_name='audience',
            name='community',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audience_in_community', to='community.community'),
        ),
    ]
