# Generated by Django 3.2.14 on 2023-06-14 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0025_alter_audience_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='audience',
            name='audience_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
