# Generated by Django 3.2.14 on 2023-07-06 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0027_storystatusconfig'),
    ]

    operations = [
        migrations.AlterField(
            model_name='copycode',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
