# Generated by Django 3.2.14 on 2023-07-25 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0028_alter_copycode_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='communitychannel',
            name='meta_data',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
