# Generated by Django 3.2.14 on 2023-07-28 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0029_communitychannel_meta_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='communitychannel',
            name='api_key',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='communitychannel',
            name='url',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
