# Generated by Django 3.2.14 on 2023-07-26 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0029_communitychannel_meta_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='communitychannel',
            name='api_key',
        ),
        migrations.RemoveField(
            model_name='communitychannel',
            name='url',
        ),
    ]
