# Generated by Django 3.2.14 on 2023-07-28 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0030_auto_20230728_0500'),
    ]

    operations = [
        migrations.AlterField(
            model_name='communitychannel',
            name='meta_data',
            field=models.JSONField(default=dict),
        ),
    ]
