# Generated by Django 4.1.1 on 2022-09-27 06:33

import administrator.models
import autoslug.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('is_trashed', models.BooleanField(default=False)),
                ('message', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('date_time', models.DateTimeField(auto_now_add=True)),
                ('activity_type', models.CharField(choices=[('0', 'Chat'), ('1', 'Follow Up Request'), ('2', 'Rating')], default='0', max_length=30)),
            ],
            options={
                'verbose_name_plural': 'Activities',
            },
        ),
        migrations.CreateModel(
            name='ActivityAttachments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('is_trashed', models.BooleanField(default=False)),
                ('activity_attachments', models.FileField(blank=True, null=True, upload_to='activity_attachments', validators=[administrator.models.validate_attachment])),
            ],
            options={
                'verbose_name_plural': 'Activity Attachments',
            },
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('is_trashed', models.BooleanField(default=False)),
                ('answer', models.CharField(max_length=200)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('is_trashed', models.BooleanField(default=False)),
                ('category_name', models.CharField(max_length=50)),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='category_name')),
                ('description', models.TextField(blank=True, default=None, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Category',
            },
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('is_trashed', models.BooleanField(default=False)),
                ('title', models.CharField(max_length=250)),
                ('description', models.TextField(blank=True, default=None, null=True)),
                ('job_type', models.CharField(choices=[('0', 'Fixed'), ('1', 'Hourly')], default='0', max_length=30)),
                ('expected_delivery_date', models.DateField(default=None)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tags', models.CharField(max_length=10000)),
                ('image_url', models.CharField(blank=True, default=None, max_length=50000, null=True)),
                ('sample_work_url', models.CharField(blank=True, default=None, max_length=50000, null=True)),
                ('job_due_date', models.DateField(auto_now_add=True)),
                ('due_date_index', models.IntegerField(blank=True, null=True)),
                ('template_name', models.CharField(blank=True, max_length=250, null=True)),
                ('status', models.IntegerField(choices=[(0, 'Draft'), (1, 'Template'), (2, 'Post')], default=2)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Job',
            },
        ),
        migrations.CreateModel(
            name='JobApplied',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('is_trashed', models.BooleanField(default=False)),
                ('cover_letter', models.TextField(blank=True, default=None, null=True)),
                ('job_bid_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('links', models.CharField(blank=True, default=None, max_length=50000, null=True)),
                ('offer_price', models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=10, null=True)),
                ('due_date', models.DateField(blank=True, default=None, null=True)),
                ('proposed_price', models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=10, null=True)),
                ('proposed_due_date', models.DateField(blank=True, default=None, null=True)),
                ('question', models.TextField(blank=True, default=None, null=True)),
                ('status', models.IntegerField(choices=[(0, 'Applied'), (1, 'Reject'), (2, 'Hire')], default=0)),
                ('job_applied_date', models.DateField(auto_now_add=True)),
                ('Accepted_proposal_date', models.DateTimeField(blank=True, default=None, editable=False, null=True)),
            ],
            options={
                'verbose_name_plural': 'Jobs Applied',
            },
        ),
        migrations.CreateModel(
            name='JobAppliedAttachments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('is_trashed', models.BooleanField(default=False)),
                ('job_applied_attachments', models.FileField(blank=True, null=True, upload_to='job_applied_attachments')),
            ],
            options={
                'verbose_name_plural': 'Job Applied Attachments',
            },
        ),
        migrations.CreateModel(
            name='JobAttachments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('is_trashed', models.BooleanField(default=False)),
                ('job_images', models.FileField(blank=True, null=True, upload_to='job_images')),
                ('work_sample_images', models.FileField(blank=True, null=True, upload_to='work_sample_images')),
            ],
            options={
                'verbose_name_plural': 'Job Attachments',
            },
        ),
        migrations.CreateModel(
            name='JobHired',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('is_trashed', models.BooleanField(default=False)),
                ('hire_date', models.DateField(auto_now_add=True)),
                ('status', models.CharField(choices=[('0', 'In progress'), ('1', 'In Review'), ('2', 'Completed'), ('3', 'Closed')], default='0', max_length=30)),
            ],
            options={
                'verbose_name_plural': 'Jobs Hired',
            },
        ),
        migrations.CreateModel(
            name='JobTasks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('is_trashed', models.BooleanField(default=False)),
                ('title', models.CharField(max_length=3000)),
                ('due_date', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Job Task',
            },
        ),
        migrations.CreateModel(
            name='JobTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('is_trashed', models.BooleanField(default=False)),
                ('template_name', models.CharField(max_length=250)),
                ('title', models.CharField(max_length=250)),
                ('description', models.TextField(blank=True, default=None, null=True)),
                ('job_type', models.IntegerField(choices=[(0, 'Fixed'), (1, 'Hourly')], default=0)),
                ('expected_delivery_date', models.DateField(default=None)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tags', models.CharField(max_length=10000)),
                ('image_url', models.CharField(blank=True, default=None, max_length=50000, null=True)),
                ('sample_work_url', models.CharField(blank=True, default=None, max_length=50000, null=True)),
                ('status', models.IntegerField(choices=[(0, 'Draft'), (1, 'Template'), (2, 'Post')], default=1)),
            ],
            options={
                'verbose_name_plural': 'Job Template',
            },
        ),
        migrations.CreateModel(
            name='JobTemplateAttachments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('is_trashed', models.BooleanField(default=False)),
                ('job_template_images', models.FileField(blank=True, null=True, upload_to='job_template_image')),
                ('work_sample_images', models.FileField(blank=True, null=True, upload_to='job_template_sample_image')),
            ],
            options={
                'verbose_name_plural': 'Job Template Attachments',
            },
        ),
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('is_trashed', models.BooleanField(default=False)),
                ('level_name', models.CharField(max_length=50)),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='level_name')),
                ('description', models.TextField(blank=True, default=None, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Level',
            },
        ),
        migrations.CreateModel(
            name='PreferredLanguage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('is_trashed', models.BooleanField(default=False)),
                ('ln_code', models.CharField(max_length=100)),
                ('ln_proficiency', models.IntegerField(choices=[(0, 'Basic'), (1, 'Intermediate'), (2, 'Fluent')], default=0)),
            ],
            options={
                'verbose_name_plural': 'Preferred Languages',
            },
        ),
        migrations.CreateModel(
            name='QA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('is_trashed', models.BooleanField(default=False)),
                ('message', models.CharField(max_length=200)),
                ('message_id', models.IntegerField(blank=True, default=None, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Skills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('is_trashed', models.BooleanField(default=False)),
                ('skill_name', models.CharField(max_length=50, unique=True)),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='skill_name')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Skills',
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('is_trashed', models.BooleanField(default=False)),
                ('question', models.CharField(max_length=200)),
                ('job_applied', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='question_job_applied', to='administrator.jobapplied')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
