# Generated by Django 4.1.1 on 2022-09-27 06:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agency', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('administrator', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='question_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='qa',
            name='job_applied',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='QA_job_applied', to='administrator.jobapplied'),
        ),
        migrations.AddField(
            model_name='qa',
            name='job_owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='QA_job_owner', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='qa',
            name='sender',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, related_name='QA_sender', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='qa',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='QA_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='preferredlanguage',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='jobtemplateattachments',
            name='job_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='job_template_images', to='administrator.jobtemplate'),
        ),
        migrations.AddField(
            model_name='jobtemplate',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jobtemplate_company', to='agency.company'),
        ),
        migrations.AddField(
            model_name='jobtemplate',
            name='industry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jobtemplate_industry', to='agency.industry'),
        ),
        migrations.AddField(
            model_name='jobtemplate',
            name='level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jobtemplate_level', to='administrator.level'),
        ),
        migrations.AddField(
            model_name='jobtemplate',
            name='skills',
            field=models.ManyToManyField(to='administrator.skills'),
        ),
        migrations.AddField(
            model_name='jobtemplate',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jobtemplate_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='jobtemplate',
            name='workflow',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jobtemplate_workflow', to='agency.worksflow'),
        ),
        migrations.AddField(
            model_name='jobtasks',
            name='job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jobtasks_job', to='administrator.job'),
        ),
        migrations.AddField(
            model_name='jobhired',
            name='job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='administrator.job'),
        ),
        migrations.AddField(
            model_name='jobhired',
            name='user',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='jobattachments',
            name='job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='images', to='administrator.job'),
        ),
        migrations.AddField(
            model_name='jobappliedattachments',
            name='job_applied',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='images', to='administrator.jobapplied'),
        ),
        migrations.AddField(
            model_name='jobapplied',
            name='job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='administrator.job'),
        ),
        migrations.AddField(
            model_name='jobapplied',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='job',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='job_company', to='agency.company'),
        ),
        migrations.AddField(
            model_name='job',
            name='industry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='job_industry', to='agency.industry'),
        ),
        migrations.AddField(
            model_name='job',
            name='level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='administrator.level'),
        ),
        migrations.AddField(
            model_name='job',
            name='related_jobs',
            field=models.ManyToManyField(blank=True, to='administrator.job'),
        ),
        migrations.AddField(
            model_name='job',
            name='skills',
            field=models.ManyToManyField(to='administrator.skills'),
        ),
        migrations.AddField(
            model_name='job',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='job',
            name='workflow',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='job_workflow', to='agency.worksflow'),
        ),
        migrations.AddField(
            model_name='answer',
            name='agency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='answer_agency', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='answer',
            name='job_applied',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='answer_job_applied', to='administrator.jobapplied'),
        ),
        migrations.AddField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, related_name='answer_question', to='administrator.question'),
        ),
        migrations.AddField(
            model_name='activityattachments',
            name='activities',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='images', to='administrator.activities'),
        ),
        migrations.AddField(
            model_name='activities',
            name='hired_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='administrator.jobhired'),
        ),
        migrations.AddField(
            model_name='activities',
            name='job_id',
            field=models.ForeignKey(blank=True, db_column='job_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='job_id', to='administrator.job'),
        ),
        migrations.AddField(
            model_name='activities',
            name='sender',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sender_id', to=settings.AUTH_USER_MODEL),
        ),
    ]
