# Generated by Django 3.2.14 on 2022-08-22 10:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflow',
            name='stage',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='administrator.stages'),
        ),
        migrations.AlterField(
            model_name='workflow',
            name='level',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='administrator.workflowlevels'),
        ),
    ]
