# Generated by Django 3.2.14 on 2022-08-22 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0002_auto_20220822_1006'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WorkFlow',
        ),
        migrations.DeleteModel(
            name='WorkFlowLevels',
        ),
    ]
