# Generated by Django 3.2.14 on 2022-09-27 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='jobtemplateattachments',
            options={'verbose_name_plural': 'Job Template_Attachments'},
        ),
        migrations.AlterField(
            model_name='job',
            name='related_jobs',
            field=models.ManyToManyField(blank=True, related_name='_administrator_job_related_jobs_+', to='administrator.Job'),
        ),
    ]
