# Generated by Django 3.2.14 on 2022-09-28 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0003_auto_20220927_1519'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplied',
            name='is_seen',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='QA',
        ),
    ]
