# Generated by Django 3.2.14 on 2022-08-23 05:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('administrator', '0006_stages_workflow_workflowlevels'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activities',
            options={},
        ),
        migrations.RenameField(
            model_name='activities',
            old_name='timestamp',
            new_name='date_time',
        ),
        migrations.RemoveField(
            model_name='activities',
            name='hired_user',
        ),
        migrations.RemoveField(
            model_name='activities',
            name='is_read',
        ),
        migrations.RemoveField(
            model_name='activities',
            name='job',
        ),
        migrations.RemoveField(
            model_name='activities',
            name='job_owner',
        ),
        migrations.RemoveField(
            model_name='activities',
            name='sender',
        ),
        migrations.AddField(
            model_name='activities',
            name='activity_attachment',
            field=models.FileField(blank=True, null=True, upload_to='activity_attachments'),
        ),
        migrations.AddField(
            model_name='activities',
            name='activity_type',
            field=models.CharField(choices=[('0', 'Chat'), ('1', 'Follow Up Request'), ('2', 'Rating')], default='0', max_length=30),
        ),
        migrations.AddField(
            model_name='activities',
            name='hired_user_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='administrator.jobhired'),
        ),
        migrations.AddField(
            model_name='activities',
            name='job_owner_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='job_owner_id', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='activities',
            name='sender_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='sender_id', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='activities',
            name='message',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
    ]
