# Generated by Django 3.2.14 on 2022-08-23 06:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0007_auto_20220823_0504'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activities',
            old_name='hired_user_id',
            new_name='hired_user',
        ),
        migrations.RenameField(
            model_name='activities',
            old_name='job_owner_id',
            new_name='job_owner',
        ),
        migrations.RenameField(
            model_name='activities',
            old_name='sender_id',
            new_name='sender',
        ),
    ]
