# Generated by Django 3.2.14 on 2022-08-23 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0008_auto_20220823_0607'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplied',
            name='negotiable_date',
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
