# Generated by Django 3.2.14 on 2022-10-04 14:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('administrator', '0008_userskills'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userskills',
            name='skills',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_skill', to='administrator.skills'),
        ),
        migrations.AlterField(
            model_name='userskills',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='skills_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
