# Generated by Django 3.2.14 on 2022-08-23 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0009_jobapplied_negotiable_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobapplied',
            name='negotiable_date',
        ),
    ]
