# Generated by Django 3.2.14 on 2022-10-05 10:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0009_auto_20221004_1446'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='expected_delivery_date',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='job_type',
            field=models.CharField(blank=True, choices=[('0', 'Fixed'), ('1', 'Hourly')], default='0', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='skills',
            field=models.ManyToManyField(blank=True, null=True, to='administrator.Skills'),
        ),
        migrations.AlterField(
            model_name='job',
            name='tags',
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name='userskills',
            name='skill_rating',
            field=models.FloatField(default=None, null=True, validators=[django.core.validators.MaxValueValidator(5.0), django.core.validators.MinValueValidator(0.1)]),
        ),
    ]
