# Generated by Django 3.2.14 on 2022-10-06 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0010_auto_20221005_1037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='skills',
            field=models.ManyToManyField(blank=True, to='administrator.Skills'),
        ),
    ]
