# Generated by Django 3.2.14 on 2022-08-23 06:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0010_remove_jobapplied_negotiable_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobAppliedAttachments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_applied_attachments', models.FileField(blank=True, null=True, upload_to='job_applied_attachments')),
                ('job_applied', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='administrator.jobapplied')),
            ],
        ),
    ]
