# Generated by Django 3.2.14 on 2022-08-24 05:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0011_jobappliedattachments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workflow',
            name='level',
        ),
        migrations.RemoveField(
            model_name='workflow',
            name='stage',
        ),
        migrations.RemoveField(
            model_name='workflow',
            name='user',
        ),
        migrations.DeleteModel(
            name='Stages',
        ),
        migrations.DeleteModel(
            name='WorkFlow',
        ),
        migrations.DeleteModel(
            name='WorkFlowLevels',
        ),
    ]
