# Generated by Django 3.2.14 on 2022-08-24 06:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0012_auto_20220824_0545'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityAttachments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_attachments', models.FileField(blank=True, null=True, upload_to='activity_attachments')),
                ('activities', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='administrator.activities')),
            ],
        ),
    ]
