# Generated by Django 3.2.14 on 2022-08-24 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0013_activityattachments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activities',
            name='activity_attachment',
        ),
    ]
