# Generated by Django 3.2.14 on 2022-10-17 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0015_auto_20221014_1331'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='is_blocked',
            field=models.BooleanField(default=False),
        ),
    ]
