# Generated by Django 3.2.14 on 2022-10-18 12:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('administrator', '0017_jobactivity_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobactivity',
            name='activity_status',
            field=models.IntegerField(choices=[(0, 'Notification'), (1, 'Chat')], default=0),
        ),
        migrations.AlterField(
            model_name='jobactivity',
            name='activity_type',
            field=models.IntegerField(blank=True, choices=[(0, 'Create'), (1, 'Updated'), (2, 'Proposal'), (3, 'Accept'), (4, 'Reject')], null=True),
        ),
        migrations.CreateModel(
            name='JobActivityChat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('is_trashed', models.BooleanField(default=False)),
                ('messages', models.CharField(max_length=2000)),
                ('is_active', models.BooleanField(default=True)),
                ('job_activity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_job_chat', to='administrator.jobactivity')),
                ('receiver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='job_activity_chat_receiver', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='job_activity_chat_sender', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Job Activities Chat',
            },
        ),
    ]
