# Generated by Django 3.2.14 on 2022-08-25 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0019_auto_20220825_1301'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobapplied',
            name='links',
        ),
    ]
