# Generated by Django 3.2.14 on 2022-08-25 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0020_remove_jobapplied_links'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplied',
            name='links',
            field=models.CharField(blank=True, default=None, max_length=50000, null=True),
        ),
    ]
