# Generated by Django 3.2.14 on 2022-11-04 14:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0020_alter_jobapplied_job'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobTemplateTasks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('is_trashed', models.BooleanField(default=False)),
                ('title', models.CharField(max_length=3000)),
                ('due_date', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
                ('job_template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jobtemplate_tasks', to='administrator.jobtemplate')),
            ],
            options={
                'verbose_name_plural': 'Job Template Task',
            },
        ),
    ]
