# Generated by Django 3.2.14 on 2022-08-26 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0021_jobapplied_links'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='image_url',
            field=models.CharField(blank=True, default=None, max_length=50000, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='sample_work_url',
            field=models.CharField(blank=True, default=None, max_length=50000, null=True),
        ),
        migrations.AddField(
            model_name='jobattachments',
            name='work_sample_images',
            field=models.FileField(blank=True, null=True, upload_to='work_sample_images'),
        ),
    ]
