# Generated by Django 3.2.14 on 2022-11-06 11:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0017_auto_20221106_1131'),
        ('administrator', '0021_jobtemplatetasks'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubmitJobWork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('is_trashed', models.BooleanField(default=False)),
                ('message', models.CharField(max_length=5000)),
                ('status', models.IntegerField(choices=[(1, 'Approved'), (2, 'Rejected'), (0, 'Pending')], default=0)),
                ('job_applied', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submit_work', to='administrator.jobapplied')),
            ],
            options={
                'verbose_name_plural': 'Submit Job Work',
            },
        ),
        migrations.CreateModel(
            name='MemberApprovals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('is_trashed', models.BooleanField(default=False)),
                ('status', models.IntegerField(choices=[(1, 'Approved'), (2, 'Rejected'), (0, 'Pending')], default=0)),
                ('approver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='job_approvers', to='agency.invitemember')),
                ('job_work', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='job_submit', to='administrator.submitjobwork')),
            ],
            options={
                'verbose_name_plural': 'Member Approvals',
            },
        ),
        migrations.CreateModel(
            name='JobWorkAttachments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('is_trashed', models.BooleanField(default=False)),
                ('work_attachments', models.FileField(blank=True, null=True, upload_to='work_attachments')),
                ('job_work', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='job_submit_Work', to='administrator.submitjobwork')),
            ],
            options={
                'verbose_name_plural': 'Job Template_Attachments',
            },
        ),
        migrations.CreateModel(
            name='JobActivityAttachments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('is_trashed', models.BooleanField(default=False)),
                ('chat_attachment', models.FileField(blank=True, default=None, null=True, upload_to='activity_chat_attachments')),
                ('job_activity_chat', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_job_attachments', to='administrator.jobactivity')),
            ],
            options={
                'verbose_name_plural': 'Job Activity Attachments',
            },
        ),
    ]
