# Generated by Django 3.2.14 on 2022-08-26 14:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0022_auto_20220826_1328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='administrator.level'),
        ),
    ]
