# Generated by Django 3.2.14 on 2022-11-07 10:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0023_submitjobwork_submit_job_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='submitjobwork',
            name='task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submit_task', to='administrator.jobtasks'),
        ),
    ]
