# Generated by Django 3.2.14 on 2022-08-30 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0024_auto_20220830_0654'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobapplied',
            old_name='porposed_due_date',
            new_name='proposed_due_date',
        ),
        migrations.RenameField(
            model_name='jobapplied',
            old_name='porposed_price',
            new_name='proposed_price',
        ),
    ]
