# Generated by Django 3.2.14 on 2022-11-07 14:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0024_submitjobwork_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='memberapprovals',
            name='message',
            field=models.CharField(blank=True, default=None, max_length=50000, null=True),
        ),
        migrations.AlterField(
            model_name='jobactivityattachments',
            name='job_activity_chat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_job_attachments', to='administrator.jobactivitychat'),
        ),
    ]
