# Generated by Django 3.2.14 on 2022-08-31 05:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('administrator', '0025_auto_20220830_0731'),
    ]

    operations = [
        migrations.CreateModel(
            name='PreferredLanguage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('ln_code', models.CharField(default=None, max_length=100)),
                ('ln_proficiency', models.IntegerField(choices=[(0, 'Basic'), (1, 'Intermediate'), (2, 'Fluent')], default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Preferred Language',
                'verbose_name_plural': 'Preferred Languages',
            },
        ),
    ]
