# Generated by Django 3.2.14 on 2022-11-08 11:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0020_auto_20221108_1117'),
        ('administrator', '0025_auto_20221107_1424'),
    ]

    operations = [
        migrations.AddField(
            model_name='memberapprovals',
            name='workflow_stage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='job_stages', to='agency.workflow_stages'),
        ),
    ]
