# Generated by Django 3.2.14 on 2022-08-31 05:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0026_preferredlanguage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='preferredlanguage',
            name='ln_code',
        ),
        migrations.RemoveField(
            model_name='preferredlanguage',
            name='ln_proficiency',
        ),
    ]
