# Generated by Django 3.2.14 on 2022-11-08 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0026_memberapprovals_workflow_stage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobactivitychat',
            name='messages',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='submitjobwork',
            name='message',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
    ]
