# Generated by Django 3.2.14 on 2022-08-31 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0027_auto_20220831_0557'),
    ]

    operations = [
        migrations.AddField(
            model_name='preferredlanguage',
            name='ln_code',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='preferredlanguage',
            name='ln_proficiency',
            field=models.IntegerField(choices=[(0, 'Basic'), (1, 'Intermediate'), (2, 'Fluent')], default=0),
        ),
    ]
