# Generated by Django 3.2.14 on 2022-08-31 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0028_auto_20220831_0557'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preferredlanguage',
            name='ln_code',
            field=models.CharField(max_length=100),
        ),
    ]
