# Generated by Django 3.2.14 on 2022-11-09 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0028_auto_20221109_1005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobactivity',
            name='activity_type',
            field=models.IntegerField(blank=True, choices=[(0, 'Create'), (1, 'Updated'), (2, 'Proposal'), (3, 'Accept'), (4, 'Reject'), (5, 'Moved'), (6, 'Completed')], null=True),
        ),
    ]
