# Generated by Django 3.2.14 on 2022-09-01 11:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0029_alter_preferredlanguage_ln_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='level',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='administrator.level'),
        ),
    ]
