# Generated by Django 3.2.14 on 2022-09-01 11:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0030_alter_job_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='administrator.level'),
        ),
    ]
