# Generated by Django 3.2.14 on 2022-11-10 13:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0026_auto_20221110_1013'),
        ('administrator', '0031_jobattachments_dam_media_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobattachments',
            name='dam_media_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='agency.dammedia'),
        ),
    ]
