# Generated by Django 3.2.14 on 2022-11-15 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0032_alter_jobattachments_dam_media_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobtasks',
            name='is_complete',
            field=models.BooleanField(default=False),
        ),
    ]
