# Generated by Django 3.2.14 on 2022-09-05 13:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0033_auto_20220905_1143'),
    ]

    operations = [
        migrations.AddField(
            model_name='activities',
            name='job_id',
            field=models.ForeignKey(db_column='job_id', default=None, on_delete=django.db.models.deletion.CASCADE, related_name='job_id', to='administrator.job'),
        ),
    ]
