# Generated by Django 3.2.14 on 2022-12-06 12:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0040_alter_dam_company'),
        ('administrator', '0036_memberapprovals_nudge_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='house_member',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='agency.invitemember'),
        ),
        migrations.AddField(
            model_name='job',
            name='is_house_member',
            field=models.BooleanField(default=False),
        ),
    ]
