# Generated by Django 3.2.14 on 2022-09-06 06:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0037_auto_20220906_0551'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobapplied',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='administrator.job'),
        ),
    ]
