# Generated by Django 3.2.14 on 2022-12-07 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0040_alter_dam_company'),
        ('administrator', '0037_auto_20221206_1214'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobtemplate',
            name='house_member',
            field=models.ManyToManyField(blank=True, to='agency.InviteMember'),
        ),
        migrations.AddField(
            model_name='jobtemplate',
            name='is_house_member',
            field=models.BooleanField(default=False),
        ),
        migrations.RemoveField(
            model_name='job',
            name='house_member',
        ),
        migrations.AddField(
            model_name='job',
            name='house_member',
            field=models.ManyToManyField(blank=True, to='agency.InviteMember'),
        ),
        migrations.AlterField(
            model_name='jobtemplate',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='jobtemplate',
            name='skills',
            field=models.ManyToManyField(blank=True, to='administrator.Skills'),
        ),
        migrations.AlterField(
            model_name='jobtemplate',
            name='tags',
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
    ]
