# Generated by Django 3.2.14 on 2022-09-06 06:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('administrator', '0039_auto_20220906_0622'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activities',
            name='hired_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='administrator.jobhired'),
        ),
        migrations.AlterField(
            model_name='activityattachments',
            name='activities',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='images', to='administrator.activities'),
        ),
        migrations.AlterField(
            model_name='job',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='administrator.category'),
        ),
        migrations.AlterField(
            model_name='job',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='administrator.company'),
        ),
        migrations.AlterField(
            model_name='job',
            name='industry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='administrator.industry'),
        ),
        migrations.AlterField(
            model_name='job',
            name='level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='administrator.level'),
        ),
        migrations.AlterField(
            model_name='job',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='jobattachments',
            name='job',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, related_name='images', to='administrator.job'),
        ),
    ]
