# Generated by Django 3.2.14 on 2022-12-12 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0039_jobfeedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobactivity',
            name='activity_by',
            field=models.IntegerField(choices=[(0, 'Agency'), (1, 'Creator')], default=0),
        ),
        migrations.AlterField(
            model_name='jobactivity',
            name='activity_type',
            field=models.IntegerField(blank=True, choices=[(0, 'Create'), (1, 'Updated'), (2, 'Proposal'), (3, 'Accept'), (4, 'Reject'), (5, 'Moved'), (6, 'Completed'), (7, 'Rating')], null=True),
        ),
    ]
