# Generated by Django 3.2.14 on 2022-09-06 06:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0040_auto_20220906_0624'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activities',
            name='job_id',
            field=models.ForeignKey(db_column='job_id', on_delete=django.db.models.deletion.DO_NOTHING, related_name='job_id', to='administrator.job'),
        ),
    ]
