# Generated by Django 3.2.14 on 2022-09-06 06:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0041_alter_activities_job_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activities',
            name='job_id',
            field=models.ForeignKey(blank=True, db_column='job_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='job_id', to='administrator.job'),
        ),
    ]
