# Generated by Django 3.2.14 on 2022-09-06 06:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0042_alter_activities_job_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobhired',
            name='job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='administrator.job'),
        ),
    ]
