# Generated by Django 3.2.14 on 2022-09-06 06:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0043_alter_jobhired_job'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobapplied',
            name='job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='administrator.job'),
        ),
        migrations.AlterField(
            model_name='jobappliedattachments',
            name='job_applied',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='images', to='administrator.jobapplied'),
        ),
        migrations.AlterField(
            model_name='jobattachments',
            name='job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='images', to='administrator.job'),
        ),
    ]
