# Generated by Django 3.2.14 on 2022-09-06 06:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('administrator', '0044_auto_20220906_0633'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activities',
            name='hired_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='administrator.jobhired'),
        ),
        migrations.AlterField(
            model_name='activities',
            name='job_owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='job_owner_id', to=settings.AUTH_USER_MODEL),
        ),
    ]
