# Generated by Django 3.2.14 on 2023-06-20 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0045_job_create_job_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='memberapprovals',
            name='work_attachment',
            field=models.FileField(blank=True, default=None, null=True, upload_to='member_approval_job_work_attachments'),
        ),
    ]
