# Generated by Django 3.2.14 on 2022-09-06 06:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0045_auto_20220906_0635'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activities',
            name='job_owner',
        ),
    ]
