# Generated by Django 3.2.14 on 2022-09-06 06:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0046_remove_activities_job_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobapplied',
            name='job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='administrator.job'),
        ),
    ]
