# Generated by Django 3.2.14 on 2023-06-21 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0046_memberapprovals_work_attachment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobworkactivity',
            name='work_activity',
            field=models.CharField(blank=True, choices=[('approved', 'approved'), ('rejected', 'rejected'), ('moved', 'moved'), ('submit_approval', 'submit_approval'), ('pending', 'pending')], max_length=30, null=True),
        ),
    ]
