# Generated by Django 3.2.14 on 2022-09-06 07:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0049_alter_jobhired_job'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activities',
            options={'verbose_name_plural': 'Activities'},
        ),
        migrations.AlterModelOptions(
            name='activityattachments',
            options={'verbose_name_plural': 'Activity Attachments'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Category'},
        ),
        migrations.AlterModelOptions(
            name='company',
            options={'verbose_name_plural': 'Company'},
        ),
        migrations.AlterModelOptions(
            name='industry',
            options={'verbose_name_plural': 'Industry'},
        ),
        migrations.AlterModelOptions(
            name='job',
            options={'verbose_name_plural': 'Job'},
        ),
        migrations.AlterModelOptions(
            name='jobapplied',
            options={'verbose_name_plural': 'Job Applied'},
        ),
        migrations.AlterModelOptions(
            name='jobappliedattachments',
            options={'verbose_name_plural': 'Job Applied Attachments'},
        ),
        migrations.AlterModelOptions(
            name='jobattachments',
            options={'verbose_name_plural': 'Job Attachments'},
        ),
        migrations.AlterModelOptions(
            name='jobhired',
            options={'verbose_name_plural': 'Job Hired'},
        ),
        migrations.AlterModelOptions(
            name='level',
            options={'verbose_name_plural': 'Level'},
        ),
        migrations.AlterModelOptions(
            name='skills',
            options={'verbose_name_plural': 'Skills'},
        ),
    ]
