# Generated by Django 3.2.14 on 2022-09-06 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0050_auto_20220906_0700'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activityattachments',
            options={'verbose_name': 'Activity Attachments'},
        ),
    ]
