# Generated by Django 3.2.14 on 2022-09-06 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0051_alter_activityattachments_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activityattachments',
            options={'verbose_name_plural': 'Activity Attachments'},
        ),
    ]
