# Generated by Django 3.2.14 on 2022-09-07 06:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0034_remove_worksflow_job'),
        ('administrator', '0054_auto_20220906_1155'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='workflow',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workflow_job', to='agency.worksflow'),
        ),
    ]
