# Generated by Django 3.2.14 on 2022-09-08 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0057_jobtasks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobtasks',
            name='due_date',
            field=models.DateField(),
        ),
    ]
