# Generated by Django 3.2.14 on 2022-09-08 12:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('agency', '0036_worksflow_company'),
        ('administrator', '0058_alter_jobtasks_due_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('is_trashed', models.BooleanField(default=False)),
                ('title', models.CharField(max_length=250)),
                ('description', models.TextField(blank=True, default=None, null=True)),
                ('job_type', models.IntegerField(choices=[(0, 'Fixed'), (1, 'Hourly')], default=0)),
                ('expected_delivery_date', models.DateField(default=None)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tags', models.CharField(max_length=10000)),
                ('image_url', models.CharField(blank=True, default=None, max_length=50000, null=True)),
                ('sample_work_url', models.CharField(blank=True, default=None, max_length=50000, null=True)),
                ('status', models.IntegerField(choices=[(0, 'Draft'), (1, 'Template')], default=1)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jobtemplate_company', to='agency.company')),
                ('level', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jobtemplate_level', to='administrator.level')),
                ('skills', models.ManyToManyField(to='administrator.Skills')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jobtemplate_user', to=settings.AUTH_USER_MODEL)),
                ('workflow', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jobtemplate_workflow', to='agency.worksflow')),
            ],
            options={
                'verbose_name_plural': 'Job Template',
            },
        ),
    ]
