# Generated by Django 3.2.14 on 2022-09-08 13:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0059_jobtemplate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='status',
            field=models.IntegerField(choices=[(0, 'Draft'), (1, 'Template'), (2, 'Post')], default=2),
        ),
        migrations.AlterField(
            model_name='jobtemplate',
            name='status',
            field=models.IntegerField(choices=[(0, 'Draft'), (1, 'Template'), (2, 'Post')], default=1),
        ),
        migrations.CreateModel(
            name='JobTemplateAttachments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('is_trashed', models.BooleanField(default=False)),
                ('job_images', models.FileField(blank=True, null=True, upload_to='jobtempalate_images')),
                ('work_sample_images', models.FileField(blank=True, null=True, upload_to='jobtempalate_work_sample_images')),
                ('job_template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jobtempalate_images', to='administrator.jobtemplate')),
            ],
            options={
                'verbose_name_plural': 'Job Template Attachments',
            },
        ),
    ]
