# Generated by Django 3.2.14 on 2022-09-09 05:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0037_remove_company_industry'),
        ('administrator', '0060_auto_20220908_1318'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='industry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='job_industry', to='agency.industry'),
        ),
        migrations.AddField(
            model_name='jobtemplate',
            name='industry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jobtemplate_industry', to='agency.industry'),
        ),
    ]
