# Generated by Django 3.2.14 on 2022-09-09 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0061_auto_20220909_0559'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobtemplate',
            name='template_name',
            field=models.CharField(default=None, max_length=250),
            preserve_default=False,
        ),
    ]
