# Generated by Django 3.2.14 on 2022-09-09 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0062_jobtemplate_template_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobtemplate',
            name='template_name',
            field=models.CharField(blank=True, default=None, max_length=250, null=True),
        ),
    ]
