# Generated by Django 3.2.14 on 2022-09-09 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0064_alter_jobtemplate_template_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobtemplate',
            name='template_name',
        ),
    ]
