# Generated by Django 3.2.14 on 2022-09-12 07:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0066_jobtemplate_template_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='job_due_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
