# Generated by Django 3.2.14 on 2022-09-14 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0067_job_job_due_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='template_name',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
