# Generated by Django 3.2.14 on 2022-09-16 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0068_job_template_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='due_date_index',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
