# Generated by Django 3.2.14 on 2022-09-14 07:58

import administrator.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0068_job_template_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='template_name',
            field=models.CharField(blank=True, max_length=250, null=True, validators=[administrator.models.validate_template_name]),
        ),
        migrations.AlterField(
            model_name='jobtemplate',
            name='template_name',
            field=models.CharField(max_length=250, validators=[administrator.models.validate_template_name]),
        ),
    ]
