# Generated by Django 3.2.14 on 2022-09-16 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0069_job_due_date_index'),
    ]

    operations = [
        migrations.DeleteModel(
            name='JobTemplateAttachments',
        ),
    ]
