# Generated by Django 3.2.14 on 2022-09-16 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0071_jobtemplateattachments'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobtemplateattachments',
            old_name='job_images',
            new_name='job_template_images',
        ),
    ]
