# Generated by Django 3.2.14 on 2022-09-19 05:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0072_rename_job_images_jobtemplateattachments_job_template_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobtemplateattachments',
            name='job_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='job_template_images', to='administrator.jobtemplate'),
        ),
        migrations.AlterField(
            model_name='jobtemplateattachments',
            name='job_template_images',
            field=models.FileField(blank=True, null=True, upload_to='job_template_images/'),
        ),
        migrations.AlterField(
            model_name='jobtemplateattachments',
            name='work_sample_images',
            field=models.FileField(blank=True, null=True, upload_to='job_template_work_sample_images/'),
        ),
    ]
