# Generated by Django 3.2.14 on 2022-09-19 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0073_auto_20220919_0519'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobtemplateattachments',
            name='job_template_images',
            field=models.FileField(blank=True, null=True, upload_to='job_template_images'),
        ),
        migrations.AlterField(
            model_name='jobtemplateattachments',
            name='work_sample_images',
            field=models.FileField(blank=True, null=True, upload_to='job_template_work_sample_images'),
        ),
    ]
