# Generated by Django 3.2.14 on 2022-09-19 07:24

import administrator.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0074_auto_20220919_0713'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobtemplateattachments',
            name='job_template_images',
            field=models.FileField(blank=True, null=True, upload_to=administrator.models.file_generate_upload_path),
        ),
        migrations.AlterField(
            model_name='jobtemplateattachments',
            name='work_sample_images',
            field=models.FileField(blank=True, null=True, upload_to=administrator.models.file_generate_upload_path),
        ),
    ]
