# Generated by Django 3.2.14 on 2022-09-20 06:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0075_auto_20220919_0724'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobapplied',
            name='cover_letter',
        ),
        migrations.RemoveField(
            model_name='jobapplied',
            name='duration',
        ),
    ]
