# Generated by Django 3.2.14 on 2022-07-11 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[(1, 'Creator'), (1, 'Agency')], default=1, max_length=30),
        ),
    ]
