# Generated by Django 3.2.14 on 2022-07-11 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_customuser_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.IntegerField(choices=[(1, 'Creator'), (2, 'Agency')], default=1, max_length=30),
        ),
    ]
