# Generated by Django 3.2.14 on 2022-10-04 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_delete_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='availability',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
