# Generated by Django 3.2.14 on 2022-07-11 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_auto_20220711_1308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.IntegerField(blank=True, choices=[(1, 'Creator'), (2, 'Agency')], default=1, max_length=30, null=True),
        ),
    ]
