# Generated by Django 3.2.14 on 2022-10-27 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_alter_customuserportfolio_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.IntegerField(choices=[(0, 'Admin'), (1, 'Creator'), (2, 'Agency'), (3, 'Member')], default=1),
        ),
    ]
