# Generated by Django 3.2.14 on 2022-11-01 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_alter_customuser_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_account_closed',
            field=models.BooleanField(default=False),
        ),
    ]
