# Generated by Django 3.2.14 on 2022-11-04 05:50

import authentication.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_customuser_is_account_closed'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('is_trashed', models.BooleanField(default=False)),
                ('profile_title', models.CharField(blank=True, max_length=200, null=True)),
                ('profile_description', models.TextField(blank=True, null=True)),
                ('profile_img', models.ImageField(blank=True, null=True, upload_to='user_profile_images/', validators=[authentication.models.validate_image])),
                ('video', models.FileField(blank=True, null=True, upload_to='user_video/', validators=[authentication.models.validate_video_extension])),
                ('profile_status', models.IntegerField(choices=[(0, 'Away'), (1, 'Online'), (2, 'Offline')], default=1)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UserCommunicationMode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('is_trashed', models.BooleanField(default=False)),
                ('communication_mode', models.IntegerField(choices=[(0, 'Email'), (1, 'Sms'), (2, 'Whatsapp'), (3, 'Slack')], default=0)),
                ('mode_value', models.CharField(blank=True, max_length=1000, null=True)),
                ('is_preferred', models.BooleanField(default=False)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_communication_mode', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'User Communication Mode',
            },
        ),
    ]
