# Generated by Django 3.2.14 on 2022-07-12 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_alter_customuser_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.IntegerField(choices=[(1, 'Creator'), (2, 'Agency')], default=1),
        ),
    ]
