# Generated by Django 3.2.14 on 2022-07-26 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0008_alter_customuser_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='portfolio',
            field=models.FileField(blank=True, null=True, upload_to='user_portfolio'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='user_video'),
        ),
    ]
