# Generated by Django 3.2.14 on 2022-11-07 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0008_usercommunicationmode_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='sub_title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
