# Generated by Django 3.2.14 on 2022-07-26 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0009_auto_20220726_1040'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='profile_img',
            field=models.ImageField(blank=True, null=True, upload_to='user_profile_images/'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='portfolio',
            field=models.FileField(blank=True, null=True, upload_to='user_portfolio/'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='user_video/'),
        ),
    ]
