# Generated by Django 3.2.14 on 2022-11-21 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0010_auto_20221115_1512'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercommunicationmode',
            name='mode_value',
            field=models.CharField(default=None, max_length=1000),
        ),
    ]
