# Generated by Django 3.2.14 on 2022-12-27 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0011_alter_usercommunicationmode_mode_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_inactive',
            field=models.BooleanField(default=False),
        ),
    ]
