# Generated by Django 3.2.14 on 2022-07-27 10:26

import authentication.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0013_alter_customuser_profile_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='profile_img',
            field=models.ImageField(blank=True, null=True, upload_to='user_profile_images/', validators=[authentication.models.validate_image]),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='user_video/', validators=[authentication.models.validate_video_extension]),
        ),
    ]
