# Generated by Django 3.2.14 on 2022-07-29 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0014_auto_20220727_1026'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='profile_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='profile_title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
