# Generated by Django 3.2.14 on 2022-08-08 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0015_auto_20220729_1046'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='profile_status',
            field=models.CharField(choices=[('0', 'away'), ('1', 'online'), ('2', 'offline')], default='1', max_length=30),
        ),
    ]
