# Generated by Django 3.2.14 on 2022-08-19 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0016_customuser_profile_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='preferred_communication_mode',
            field=models.CharField(choices=[('0', 'Email'), ('1', 'Whatsapp'), ('2', 'Instagram'), ('3', 'Facebook'), ('4', 'Linkedin')], default='0', max_length=30),
        ),
    ]
