# Generated by Django 3.2.14 on 2022-08-30 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0019_alter_customuser_preferred_communication_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_exclusive',
            field=models.BooleanField(default=False),
        ),
    ]
