# Generated by Django 3.2.14 on 2022-09-01 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0020_customuser_is_exclusive'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='preferred_communication_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
