# Generated by Django 3.2.14 on 2022-09-02 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0022_paymentmethod'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('clientPayerId', models.CharField(blank=True, max_length=100, null=True)),
                ('tintype', models.CharField(blank=True, default='Individual', max_length=200, null=True)),
                ('payerTin', models.CharField(blank=True, max_length=100, null=True)),
                ('first_name', models.CharField(blank=True, max_length=50, null=True)),
                ('middle_name', models.CharField(blank=True, max_length=50, null=True)),
                ('last_name', models.CharField(blank=True, max_length=50, null=True)),
                ('suffix', models.CharField(blank=True, max_length=50, null=True)),
                ('ssn', models.CharField(blank=True, max_length=100, null=True)),
                ('address_1', models.CharField(blank=True, max_length=250, null=True)),
                ('address_2', models.CharField(blank=True, max_length=250, null=True)),
                ('city', models.CharField(blank=True, max_length=250, null=True)),
                ('state', models.CharField(blank=True, max_length=50, null=True)),
                ('zipcode', models.CharField(blank=True, max_length=13, null=True)),
                ('country', models.CharField(blank=True, default='US', max_length=50, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=13, null=True)),
                ('email', models.CharField(blank=True, max_length=100, null=True)),
                ('last_filing', models.BooleanField(default=True)),
                ('combined_fed_state_filing', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
