# Generated by Django 3.2.14 on 2022-09-05 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0023_paymentdetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_trashed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='paymentdetails',
            name='is_trashed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='paymentmethod',
            name='is_trashed',
            field=models.BooleanField(default=False),
        ),
    ]
