# Generated by Django 3.2.14 on 2022-09-06 06:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0024_auto_20220905_1158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuserportfolio',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.SET_DEFAULT, to=settings.AUTH_USER_MODEL),
        ),
    ]
