# Generated by Django 3.2.14 on 2022-09-06 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0026_alter_customuserportfolio_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='is_trashed',
        ),
    ]
