# Generated by Django 3.2.14 on 2022-09-06 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0027_remove_customuser_is_trashed'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_trashed',
            field=models.BooleanField(default=False),
        ),
    ]
