# Generated by Django 3.2.14 on 2022-09-06 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0028_customuser_is_trashed'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuserportfolio',
            options={'verbose_name_plural': 'CustomUser Portfolio'},
        ),
        migrations.AlterModelOptions(
            name='paymentdetails',
            options={'verbose_name_plural': 'Payment Details'},
        ),
        migrations.AlterModelOptions(
            name='paymentmethod',
            options={'verbose_name_plural': 'Payment Method'},
        ),
    ]
