TAG_CREATED = "Tag created successfully!"
STORIES_RETRIEVE_SUCCESSFULLY = "Stories retrieved successfully!"
COMMUNITY_TAGS_RETRIEVE_SUCCESSFULLY = "Community Tags retrieved successfully!"
COMMUNITY_TAGS_STATUS_DATA = "Community, Status, Tags data retrieved successfully!"
COMMUNITY_SETTINGS_RETRIEVE_SUCCESSFULLY = "Community settings data retrieved successfully!"
COMMUNITY_SETTINGS_SUCCESS = "Community settings created successfully!"
# TAGS_DATA = "Tags data retrieved successfully!"
# STATUS_DATA = "Status data retrieved successfully!"
