TAG_CREATED = "Tag created successfully!"
STORIES_RETRIEVE_SUCCESSFULLY = "Stories retrieved successfully!"
COMMUNITY_TAGS_RETRIEVE_SUCCESSFULLY = "Community Tags retrieved successfully!"
COMMUNITY_DATA = "Community data retrieved successfully!"
TAGS_DATA = "Tags data retrieved successfully!"
STATUS_DATA = "Status data retrieved successfully!"
