# Generated by Django 3.2.14 on 2023-03-17 05:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('publication', '0002_auto_20230317_0547'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='publication.article')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='publication.tag')),
            ],
        ),
        migrations.AddField(
            model_name='article',
            name='tag',
            field=models.ManyToManyField(related_name='article_tag', through='publication.ArticleTag', to='publication.Tag'),
        ),
    ]
