# Generated by Django 4.1.1 on 2022-09-27 06:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agency', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='worksflow',
            name='agency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workflow_agency', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='worksflow',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workflow_company', to='agency.company'),
        ),
        migrations.AddField(
            model_name='workflow_stages',
            name='approvals',
            field=models.ManyToManyField(related_name='stage_approvals', to='agency.invitemember'),
        ),
        migrations.AddField(
            model_name='workflow_stages',
            name='observer',
            field=models.ManyToManyField(related_name='stage_observer', to='agency.invitemember'),
        ),
        migrations.AddField(
            model_name='workflow_stages',
            name='workflow',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stage_workflow', to='agency.worksflow'),
        ),
        migrations.AddField(
            model_name='invitemember',
            name='agency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invite_member_agency', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='invitemember',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invite_member_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dammedia',
            name='dam',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dam_media', to='agency.dam'),
        ),
        migrations.AddField(
            model_name='dam',
            name='agency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dam_agency', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='company',
            name='agency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='company_agency', to=settings.AUTH_USER_MODEL),
        ),
    ]
