# Generated by Django 3.2.14 on 2022-09-07 09:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('administrator', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('agency', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='worksflow',
            name='agency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workflow_agency', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='worksflow',
            name='job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workflow_job', to='administrator.job'),
        ),
        migrations.AddField(
            model_name='workflow_stages',
            name='approvals',
            field=models.ManyToManyField(related_name='stage_approvals', to='agency.InviteMember'),
        ),
        migrations.AddField(
            model_name='workflow_stages',
            name='observer',
            field=models.ManyToManyField(related_name='stage_observer', to='agency.InviteMember'),
        ),
        migrations.AddField(
            model_name='workflow_stages',
            name='workflow',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stage_workflow', to='agency.worksflow'),
        ),
        migrations.AddField(
            model_name='invitemember',
            name='agency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invite_member_agency', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='invitemember',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invite_member_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
