# Generated by Django 3.2.14 on 2022-08-25 05:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workflow',
            name='stage',
        ),
    ]
