# Generated by Django 3.2.14 on 2022-08-25 05:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0002_remove_workflow_stage'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflow',
            name='stage',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='agency.stages'),
        ),
    ]
