# Generated by Django 4.1.1 on 2022-09-27 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='testmodal',
            name='demo',
            field=models.CharField(default='', max_length=50),
        ),
    ]
