# Generated by Django 3.2.14 on 2022-09-27 15:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0004_remove_testmodal_demo'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitemember',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invite_company_list', to='agency.company'),
        ),
    ]
