# Generated by Django 3.2.14 on 2022-08-25 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0004_workflow_job_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workflow',
            name='job_owner',
        ),
    ]
