# Generated by Django 3.2.14 on 2022-10-01 11:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0005_invitemember_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='dam',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='agency.dam'),
        ),
    ]
