# Generated by Django 3.2.14 on 2022-10-04 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0006_dam_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dam',
            name='name',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
    ]
