# Generated by Django 3.2.14 on 2022-08-25 07:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0016_jobhired_status'),
        ('agency', '0007_remove_workflow_job_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflow',
            name='job_owner',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='administrator.job'),
        ),
    ]
