# Generated by Django 3.2.14 on 2022-10-19 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0008_auto_20221014_1331'),
    ]

    operations = [
        migrations.AddField(
            model_name='dam',
            name='is_favourite',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='invitemember',
            name='email',
            field=models.EmailField(blank=True, default=None, max_length=254, null=True),
        ),
    ]
