# Generated by Django 3.2.14 on 2022-08-25 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0009_auto_20220825_0731'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workflow',
            name='agency',
        ),
    ]
