# Generated by Django 3.2.14 on 2022-10-27 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0010_auto_20221020_1406'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agencylevel',
            name='levels',
            field=models.IntegerField(choices=[(1, 'Agency Admin'), (2, 'Agency Marketer'), (3, 'Agency Approver')], default=None),
        ),
    ]
