# Generated by Django 3.2.14 on 2022-08-25 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0011_workflow_agency'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workflow',
            name='agency',
        ),
    ]
