# Generated by Django 3.2.14 on 2022-10-28 14:21

import agency.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0012_auto_20221028_1216'),
    ]

    operations = [
        migrations.AddField(
            model_name='dammedia',
            name='thumbnail',
            field=models.FileField(blank=True, null=True, upload_to=agency.models.fileLocation),
        ),
    ]
