# Generated by Django 3.2.14 on 2022-10-29 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0013_dammedia_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitemember',
            name='is_blocked',
            field=models.BooleanField(default=False),
        ),
    ]
