# Generated by Django 3.2.14 on 2022-08-29 06:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('agency', '0013_workflow_agency'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflowlevels',
            name='agency',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='agency_level', to=settings.AUTH_USER_MODEL),
        ),
    ]
