# Generated by Django 3.2.14 on 2022-11-02 10:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0014_invitemember_is_blocked'),
    ]

    operations = [
        migrations.AddField(
            model_name='dammedia',
            name='image_favourite',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='dam',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='agency.dam'),
        ),
    ]
