# Generated by Django 3.2.14 on 2022-08-30 08:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('agency', '0015_stages_agency'),
    ]

    operations = [
        migrations.CreateModel(
            name='InviteMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('status', models.IntegerField(choices=[(0, 'Send'), (1, 'Accept'), (2, 'Reject')], default=0)),
                ('agency', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='invite_member_agency', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invite_member_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'InviteMember',
                'verbose_name_plural': 'InviteMembers',
            },
        ),
    ]
