# Generated by Django 3.2.14 on 2022-11-06 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0016_auto_20221104_1411'),
    ]

    operations = [
        migrations.AddField(
            model_name='dammedia',
            name='limit_usage',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='dammedia',
            name='limit_usage_toggle',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='dammedia',
            name='limit_used',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='dammedia',
            name='tags',
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
        migrations.AddField(
            model_name='dammedia',
            name='usage',
            field=models.IntegerField(blank=True, choices=[(1, 'Public'), (0, 'Private')], default=None, null=True),
        ),
    ]
