# Generated by Django 3.2.14 on 2022-08-31 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0017_worksflow'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worksflow',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
