# Generated by Django 3.2.14 on 2022-11-08 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0019_auto_20221107_1424'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dammedia',
            name='media_type',
        ),
        migrations.AddField(
            model_name='dammedia',
            name='is_video',
            field=models.BooleanField(default=False),
        ),
    ]
