# Generated by Django 3.2.14 on 2022-09-02 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0020_stage_order'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WorkFlow',
        ),
    ]
