# Generated by Django 3.2.14 on 2022-09-05 06:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0031_alter_job_level'),
        ('agency', '0021_delete_workflow'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worksflow',
            name='job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='workflow_job', to='administrator.job'),
        ),
    ]
