# Generated by Django 3.2.14 on 2022-11-10 05:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0022_auto_20221109_1429'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dammedia',
            name='limit_usage',
        ),
    ]
