# Generated by Django 3.2.14 on 2022-09-05 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0022_alter_worksflow_job'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Stage',
            new_name='Workflow_Stage',
        ),
        migrations.AlterModelOptions(
            name='workflow_stage',
            options={'verbose_name': 'Workflow Stage', 'verbose_name_plural': 'Workflow Stages'},
        ),
    ]
