# Generated by Django 3.2.14 on 2022-09-05 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0023_auto_20220905_1057'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='workflow_stage',
            options={'verbose_name': 'Workflow Stages', 'verbose_name_plural': 'Workflow Stages'},
        ),
    ]
