# Generated by Django 3.2.14 on 2022-09-05 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0024_alter_workflow_stage_options'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Workflow_Stage',
            new_name='Workflow_Stages',
        ),
    ]
