# Generated by Django 3.2.14 on 2022-09-05 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0025_rename_workflow_stage_workflow_stages'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workflowlevels',
            name='agency',
        ),
        migrations.DeleteModel(
            name='Stages',
        ),
        migrations.DeleteModel(
            name='WorkFlowLevels',
        ),
    ]
