# Generated by Django 3.2.14 on 2022-11-11 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0026_auto_20221110_1013'),
    ]

    operations = [
        migrations.AddField(
            model_name='dam',
            name='is_video',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='dam',
            name='type',
            field=models.IntegerField(choices=[(1, 'Folder'), (2, 'Collection'), (3, 'Image'), (4, 'Video')], default=None),
        ),
    ]
