# Generated by Django 3.2.14 on 2022-09-05 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0026_auto_20220905_1109'),
    ]

    operations = [
        migrations.AddField(
            model_name='worksflow',
            name='is_trashed',
            field=models.BooleanField(default=False),
        ),
    ]
