# Generated by Django 3.2.14 on 2022-09-05 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0027_worksflow_is_trashed'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitemember',
            name='is_trashed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='workflow_stages',
            name='is_trashed',
            field=models.BooleanField(default=False),
        ),
    ]
