# Generated by Django 3.2.14 on 2022-09-05 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0028_auto_20220905_1115'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invitemember',
            name='is_trashed',
        ),
        migrations.RemoveField(
            model_name='workflow_stages',
            name='is_trashed',
        ),
        migrations.RemoveField(
            model_name='worksflow',
            name='is_trashed',
        ),
    ]
