# Generated by Django 3.2.14 on 2022-11-21 08:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('agency', '0029_auto_20221115_1512'),
    ]

    operations = [
        migrations.AddField(
            model_name='dam',
            name='applied_creator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dam_creator', to=settings.AUTH_USER_MODEL),
        ),
    ]
