# Generated by Django 3.2.14 on 2022-09-05 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0029_auto_20220905_1124'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitemember',
            name='is_trashed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='workflow_stages',
            name='is_trashed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='worksflow',
            name='is_trashed',
            field=models.BooleanField(default=False),
        ),
    ]
