# Generated by Django 3.2.14 on 2022-11-29 14:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('agency', '0029_auto_20221115_1512'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='industry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='company_industry', to='agency.industry'),
        ),
        migrations.AddField(
            model_name='dam',
            name='applied_creator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dam_creator', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='industry',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Industry_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='workflow_stages',
            name='approval_time',
            field=models.IntegerField(default=36),
        ),
        migrations.AddField(
            model_name='workflow_stages',
            name='is_nudge',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='workflow_stages',
            name='nudge_time',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='dammedia',
            name='usage',
            field=models.IntegerField(choices=[(1, 'Public'), (0, 'Private')], default=1),
        ),
    ]
