# Generated by Django 3.2.14 on 2022-09-06 05:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('administrator', '0037_auto_20220906_0551'),
        ('agency', '0030_auto_20220905_1125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitemember',
            name='agency',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='invite_member_agency', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='invitemember',
            name='user',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='invite_member_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='workflow_stages',
            name='workflow',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='stage_workflow', to='agency.worksflow'),
        ),
        migrations.AlterField(
            model_name='worksflow',
            name='agency',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='workflow_agency', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='worksflow',
            name='job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workflow_job', to='administrator.job'),
        ),
    ]
