# Generated by Django 3.2.14 on 2022-11-25 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0031_company_industry'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflow_stages',
            name='approval_time',
            field=models.IntegerField(default=36),
        ),
        migrations.AlterField(
            model_name='dammedia',
            name='usage',
            field=models.IntegerField(choices=[(1, 'Public'), (0, 'Private')], default=1),
        ),
    ]
