# Generated by Django 3.2.14 on 2022-09-06 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0032_auto_20220906_0712'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='invitemember',
            options={'verbose_name_plural': 'Invite Members'},
        ),
        migrations.AlterModelOptions(
            name='workflow_stages',
            options={'verbose_name_plural': 'Workflow Stages'},
        ),
        migrations.AlterModelOptions(
            name='worksflow',
            options={'verbose_name_plural': 'WorksFlow'},
        ),
    ]
