# Generated by Django 3.2.14 on 2022-11-30 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0032_auto_20221130_1027'),
    ]

    operations = [
        migrations.AddField(
            model_name='agencylevel',
            name='is_test',
            field=models.BooleanField(default=True),
        ),
    ]
