# Generated by Django 3.2.14 on 2022-11-29 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0032_auto_20221125_1445'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workflow_stages',
            name='approval_time',
        ),
    ]
