# Generated by Django 3.2.14 on 2022-09-07 06:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0033_auto_20220906_1159'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='worksflow',
            name='job',
        ),
    ]
