# Generated by Django 3.2.14 on 2022-11-29 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0033_remove_workflow_stages_approval_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflow_stages',
            name='approval_time',
            field=models.IntegerField(default=36),
        ),
    ]
