# Generated by Django 3.2.14 on 2022-11-30 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0033_agencylevel_is_test'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agencylevel',
            name='is_test',
        ),
    ]
