# Generated by Django 3.2.14 on 2022-09-08 07:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0035_company_industry'),
    ]

    operations = [
        migrations.AddField(
            model_name='worksflow',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workflow_company', to='agency.company'),
        ),
    ]
