# Generated by Django 3.2.14 on 2022-09-09 05:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0036_worksflow_company'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='industry',
        ),
    ]
