# Generated by Django 3.2.14 on 2022-12-01 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0036_auto_20221201_1325'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workflow_stages',
            name='approval_time',
        ),
    ]
