# Generated by Django 3.2.14 on 2022-09-09 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0037_remove_company_industry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='description',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
