# Generated by Django 3.2.14 on 2022-12-01 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0037_remove_workflow_stages_approval_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflow_stages',
            name='approval_time',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
