# Generated by Django 3.2.14 on 2022-09-12 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0038_alter_company_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='industry',
            name='industry_name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
