# Generated by Django 3.2.14 on 2022-12-02 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0038_workflow_stages_approval_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workflow_stages',
            name='nudge_time',
            field=models.CharField(blank=True, default=None, max_length=50000, null=True),
        ),
    ]
