# Generated by Django 3.2.14 on 2022-12-06 12:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0039_alter_workflow_stages_nudge_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dam',
            name='company',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dam_company', to='agency.company'),
        ),
    ]
