# Generated by Django 3.2.14 on 2022-09-12 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0039_auto_20220912_0654'),
    ]

    operations = [
        migrations.AlterField(
            model_name='industry',
            name='industry_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AddConstraint(
            model_name='industry',
            constraint=models.UniqueConstraint(condition=models.Q(('is_trashed', False)), fields=('industry_name',), name='unique_undeleted_industry_name'),
        ),
    ]
