# Generated by Django 3.2.14 on 2022-12-26 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0040_alter_dam_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitemember',
            name='is_modified',
            field=models.BooleanField(default=False),
        ),
    ]
