# Generated by Django 3.2.14 on 2022-09-12 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0040_auto_20220912_0752'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterUniqueTogether(
            name='company',
            unique_together={('name', 'is_trashed')},
        ),
    ]
