# Generated by Django 3.2.14 on 2023-01-30 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0041_invitemember_is_modified'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitemember',
            name='is_inactive',
            field=models.BooleanField(default=False),
        ),
    ]
