# Generated by Django 3.2.14 on 2022-09-12 07:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0041_auto_20220912_0755'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='industry',
            name='unique_undeleted_industry_name',
        ),
        migrations.AlterUniqueTogether(
            name='industry',
            unique_together={('industry_name', 'is_trashed')},
        ),
    ]
