# Generated by Django 3.2.14 on 2022-09-12 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0042_auto_20220912_0757'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='industry',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='industry',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('industry_name',), name='unique_name_not_deleted'),
        ),
    ]
