# Generated by Django 3.2.14 on 2023-02-07 13:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('agency', '0042_invitemember_is_inactive'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dam',
            name='agency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dam_agency', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='dam',
            name='applied_creator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dam_creator', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='dam',
            name='company',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dam_company', to='agency.company'),
        ),
    ]
