# Generated by Django 3.2.14 on 2022-09-12 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0044_auto_20220912_0811'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='industry',
            name='unique_name_not_deleted',
        ),
    ]
