# Generated by Django 3.2.14 on 2023-04-12 11:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0012_auto_20230412_1116'),
        ('agency', '0044_company_created_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='Audience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('is_trashed', models.BooleanField(default=False)),
                ('audience_id', models.CharField(max_length=10)),
                ('title', models.CharField(max_length=200)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Audiences',
            },
        ),
        migrations.CreateModel(
            name='AudienceChannel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('is_trashed', models.BooleanField(default=False)),
                ('url', models.CharField(max_length=200)),
                ('audience', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audience_channel_audience', to='agency.audience')),
                ('channel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audience_channel_channel', to='community.channel')),
            ],
            options={
                'verbose_name_plural': 'AudienceChannels',
            },
        ),
        migrations.AddField(
            model_name='audience',
            name='channel',
            field=models.ManyToManyField(related_name='audience_channel', through='agency.AudienceChannel', to='community.Channel'),
        ),
    ]
