# Generated by Django 3.2.14 on 2023-04-12 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0045_auto_20230412_1116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audience',
            name='audience_id',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
