# Generated by Django 3.2.14 on 2022-09-12 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0045_remove_industry_unique_name_not_deleted'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='industry',
            constraint=models.UniqueConstraint(condition=models.Q(('is_trashed', False)), fields=('industry_name',), name='unique_name_not_deleted'),
        ),
    ]
