# Generated by Django 3.2.14 on 2023-04-28 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0046_alter_audience_audience_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='audiencechannel',
            name='url',
        ),
        migrations.AddField(
            model_name='audience',
            name='geography',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='audiencechannel',
            name='age',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='audiencechannel',
            name='device',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='audiencechannel',
            name='gender',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='audiencechannel',
            name='language',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='audiencechannel',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
