# Generated by Django 3.2.14 on 2022-09-12 09:54

import agency.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('agency', '0046_industry_unique_name_not_deleted'),
    ]

    operations = [
        migrations.CreateModel(
            name='DAM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('is_trashed', models.BooleanField(default=False)),
                ('name', models.CharField(default=None, max_length=50)),
                ('type', models.IntegerField(choices=[(1, 'Folder'), (2, 'Collection'), (3, 'Image')], default=None)),
                ('agency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dam_agency', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'DAM',
            },
        ),
        migrations.CreateModel(
            name='DamMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('is_trashed', models.BooleanField(default=False)),
                ('media', models.FileField(blank=True, null=True, upload_to=agency.models.fileLocation)),
                ('dam', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dam_media', to='agency.dam')),
            ],
            options={
                'verbose_name_plural': 'DAM Media',
            },
        ),
    ]
