# Generated by Django 3.2.14 on 2022-09-12 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0047_dam_dammedia'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='industry',
            name='unique_name_not_deleted',
        ),
    ]
