# Generated by Django 3.2.14 on 2023-05-03 06:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0020_alter_communitysetting_community'),
        ('agency', '0047_auto_20230428_0706'),
    ]

    operations = [
        migrations.AddField(
            model_name='audience',
            name='community',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audience_community', to='community.community'),
        ),
    ]
