# Generated by Django 3.2.14 on 2022-09-14 06:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0048_remove_industry_unique_name_not_deleted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='name',
            field=models.CharField(max_length=50, validators=[django.core.validators.RegexValidator('[+-/%]', inverse_match=True)]),
        ),
        migrations.AddConstraint(
            model_name='industry',
            constraint=models.UniqueConstraint(condition=models.Q(('is_trashed', False)), fields=('industry_name',), name='unique_name_not_deleted'),
        ),
    ]
