# Generated by Django 3.2.14 on 2023-06-23 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0048_audience_community'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='embedded_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
