# Generated by Django 3.2.14 on 2022-09-14 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0049_auto_20220914_0601'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
