# Generated by Django 3.2.14 on 2022-09-14 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0050_alter_company_name'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='company',
            unique_together=set(),
        ),
    ]
