# Generated by Django 3.2.14 on 2022-09-16 07:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('agency', '0051_alter_company_unique_together'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='industry',
            name='unique_name_not_deleted',
        ),
        migrations.AddField(
            model_name='company',
            name='agency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='company_agency', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='workflow_stages',
            name='is_all_approval',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='company',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
