# Generated by Django 3.2.14 on 2022-09-14 09:55

import agency.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('agency', '0053_auto_20220914_0954'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='agency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='company_agency', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='industry',
            name='industry_name',
            field=models.CharField(max_length=50, validators=[agency.models.validate_industry_name]),
        ),
    ]
