INTAKE_FORM_RETRIEVED_SUCCESSFULLY = "Intake Form retrieved successfully!"
INTAKE_FORM_CREATED_SUCCESSFULLY = "Intake Form created successfully!"
INTAKE_FORM_UPDATED_SUCCESSFULLY = "Intake Form updated successfully!"
INTAKE_FORM_SUBMIT_SUCCESS = "Your response have been recorded."
INTAKE_FORM_TASK_CREATED_SUCCESSFULLY = "Intake Form Task created successfully!"
INTAKE_FORM_TASK_UPDATED_SUCCESSFULLY = "Intake Form Task updated successfully!"
INTAKE_FORM_TASK_RETRIEVED_SUCCESSFULLY = "Intake Form Task retrieved successfully!"
